region: us
version: '2'
authtoken: 2eiWbVMmZTFyPhhKDmnAp6hjtAV_67v1bovGKHVitg1yo6rgm
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http
